-   id: check-docstrings
    name: Check docstrings
    description: This hook checks if methods longer than a certain length have docstrings.
    entry: python check_docstrings.py
    language: python
    language: script
    language_version: python3
    types: [python]
